name: Deploy to Amazon ECS

on:
  push:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        cache: yarn

    - name: Build
      env:
        REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
        REACT_APP_WS_URL: ${{ vars.REACT_APP_WS_URL }}
        REACT_APP_CHECKOUT_PUBLIC_KEY: ${{ secrets.REACT_APP_CHECKOUT_PUBLIC_KEY }}
        REACT_APP_SOCURE_PUBLIC_KEY: ${{ secrets.REACT_APP_SOCURE_PUBLIC_KEY }}
      run: |
        yarn install
        yarn build

    - name: Publish
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --relative
        path: ./build
        remote_path: /var/www/checkout-widget/
        remote_host: ${{ vars.SSH_HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.AWS_PRIVATE_KEY }}
